# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ListTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ListTest
  pod 'IGListKit', '~> 4.0.0'
  pod 'Moya', '~> 14.0'

  target 'ListTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListTestUITests' do
    # Pods for testing
  end
  
end
